### ISSUE TITLE
Functions/Labels you can jump too

### ISSUE THREAD

**Issue by poggingfish** [StiglCZ/SemiColonLang#1]
exmpl
```
_lbl:
code

jmp _lbl
```

**Comment by stigl-cc** [comment]
Theres not text in this programming language, only ;{}
Idk

**Comment by poggingfish** [comment]
you could make an exception for jmps

**Comment by stigl-cc** [comment]
Every other character than {}; is automaticly an comment

**Comment by poggingfish** [comment]
Ah well try to figure something out because this is a really useful feature

**Comment by stigl-cc** [comment]
Yea okay

**Comment by stigl-cc** [comment]
Functions were added
Execution: 11*; + Function ID
